---
# Using a 'custom_component' for now. This component will probably be part of 'core' soon.
#
# See PR: https://github.com/home-assistant/core/pull/83886
#
# https://www.home-assistant.io/integrations/energyzero/
#
energyzero:

sensor:
  - platform: rest
    name: "Gas price"
    device_class: monetary
    unit_of_measurement: "€/m³"
    method: GET
    value_template: "{{ (value_json.Prices[0].price | float(0) + (0.06839 + 0.04798000 + 0.449724771) * 1.09) | round(3) }}"
    resource_template: https://api.energyzero.nl/v1/energyprices?{{ utcnow().strftime('fromDate=%Y-%m-%dT%H:00:00.000Z&tillDate=%Y-%m-%dT%H:59:59.999Z') }}&interval=4&usageType=3&inclBtw=true

  - platform: rest
    unique_id: energyzero_gasprices_rest
    name: Gasprijs per uur
    resource: https://api.energyzero.nl/v1/energyprices
    scan_interval: 900
    unit_of_measurement: "€/m³"
    value_template: >
      {{value_json.Prices[(now()+timedelta(hours=-1)).hour].price}}
    params:
      fromDate: >
        {{(now().strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      tillDate: >
        {{((now()+ timedelta(days=2)).strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      interval: 4
      usageType: 3
      inclBtw: true
    json_attributes:
      - Prices
      - readingDate

  - platform: rest
    unique_id: energyzero_powerprices_rest
    name: Stroomprijs per uur
    resource: https://api.energyzero.nl/v1/energyprices
    scan_interval: 900
    unit_of_measurement: "€/kWh"
    value_template: >
      {{value_json.Prices[(now()+timedelta(hours=-1)).hour].price}}
    params:
      fromDate: >
        {{(now().strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      tillDate: >
        {{((now()+ timedelta(days=2)).strftime('%Y-%m-%d')|as_datetime).isoformat()}}Z
      interval: 4
      usageType: 1
      inclBtw: true
    json_attributes:
      - Prices
      - readingDate
