---
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 3238BA
    street_number: 17
    exclude_pickup_today: false

  - platform: statistics
    name: Bathroom Humidity Average Linear 24h
    entity_id: sensor.badkamer_humidity
    state_characteristic: average_linear
    sampling_size: 50
    max_age:
      hours: 24
