---
# Welcome to my Home Assistant configuration!
#
# The configuration.yaml is only used to bootstrap the system.
#
# Credit where credit is due.
#
# This setup is largely based on this: https://github.com/frenck/home-assistant-config
#
#
homeassistant:
  packages: !include_dir_named integrations
